region="ap-southeast-2"
terraform_state_bucket_name="expensely-terraform-state"
terraform_state_policy_name="terraform-ap-southeast-2-bucket"
terraform_lock_table_name="expensely-terraform-lock"
terraform_lock_policy_name="terraform-ap-southeast-2-dynamodb"
terraform_key_policy_name="terraform-ap-southeast-2-key"
